"""VS Code `.vscode` folder helpers."""
from __future__ import annotations

import re
import shlex
from pathlib import Path

from . import jsonc
from .util import read_text

DEFAULT_MARK = "Generated by ideswap"
GRADLE_EXE = re.compile(r"(^|/)(gradlew|gradle)(\.bat|\.cmd)?$", re.I)
VALUE_OPTS = {"-x", "--exclude-task", "-p", "--project-dir", "-g", "--gradle-user-home", "-I",
              "--init-script", "--console", "--warning-mode", "--priority", "--max-workers", "-c",
              "--settings-file", "-b", "--build-file"}


class JsonFile:
    def __init__(self, path: Path, default):
        self.path = Path(path)
        self.exists = self.path.is_file()
        self.had_comments = False
        self.invalid = False
        self.changed = False
        self.data = default
        if self.exists:
            try:
                data, self.had_comments = jsonc.loads(read_text(self.path))
                self.data = data if isinstance(data, dict) else default
            except ValueError:
                self.invalid = True

    def save(self, tx, report):
        if not self.changed or self.invalid:
            return
        if self.had_comments:
            report.warn(f"{self.path.name}: comments were dropped when adding entries "
                        "(the original is backed up; `ideswap undo` restores it)")
        tx.write(self.path, jsonc.dumps(self.data))


def strip_workspace(p: str | None) -> str:
    if not p:
        return ""
    p = p.replace("\\", "/")
    for var in ("${workspaceFolder}", "${workspaceRoot}"):
        p = p.replace(var, "")
    return p.strip("/")


def _quote(arg: str) -> str:
    return f'"{arg}"' if re.search(r"\s", arg) else arg


def split_gradle_args(args: list[str]) -> tuple[list[str], str]:
    tasks, opts = [], []
    it = iter(args)
    for a in it:
        if a.startswith("-"):
            opts.append(a)
            if a in VALUE_OPTS:
                nxt = next(it, None)
                if nxt is not None:
                    opts.append(nxt)
        elif a:
            tasks.append(a)
    return tasks, " ".join(_quote(o) for o in opts)


def gradle_of_task(task: dict):
    """(gradle task names, extra args string, cwd relative to workspace) for a Gradle task, else None."""
    if not isinstance(task, dict):
        return None
    if task.get("type") == "gradle":
        script = task.get("script")
        if not script:
            return None
        return [script], task.get("args", "") or "", strip_workspace(task.get("projectFolder"))
    cmd = task.get("command")
    if isinstance(cmd, dict):
        cmd = cmd.get("value")
    if not isinstance(cmd, str) or not cmd.strip():
        return None
    cmd = cmd.replace("\\", "/")
    try:
        parts = shlex.split(cmd) if re.search(r"\s", cmd.strip()) else [cmd.strip()]
    except ValueError:
        return None
    if not parts or not GRADLE_EXE.search(parts[0]):
        return None
    extra = []
    for a in task.get("args", []) or []:
        extra.append(a if isinstance(a, str) else (a.get("value", "") if isinstance(a, dict) else str(a)))
    tasks, opts = split_gradle_args(parts[1:] + extra)
    if not tasks:
        return None
    cwd = strip_workspace((task.get("options") or {}).get("cwd"))
    return tasks, opts, cwd


def gradle_task(label: str, tasks: list[str], args: str = "", cwd: str = "",
                group=None, default=False, generated=False) -> dict:
    t: dict = {"label": label, "type": "shell", "command": "./gradlew",
               "windows": {"command": ".\\gradlew.bat"},
               "args": list(tasks) + (shlex.split(args) if args else [])}
    if cwd:
        t["options"] = {"cwd": "${workspaceFolder}/" + cwd}
    if group:
        t["group"] = {"kind": group, "isDefault": True} if default else group
    if generated:
        t["detail"] = DEFAULT_MARK
    t["problemMatcher"] = []
    return t


def shell_task(label: str, command: str, args: list[str], cwd: str = "", depends: str | None = None) -> dict:
    t: dict = {"label": label, "type": "shell", "command": command, "args": args}
    if cwd:
        t["options"] = {"cwd": "${workspaceFolder}/" + cwd}
    if depends:
        t["dependsOn"] = depends
    t["detail"] = DEFAULT_MARK
    t["problemMatcher"] = []
    return t


def args_list(value) -> str:
    if isinstance(value, list):
        return " ".join(_quote(str(v)) for v in value)
    return value or ""
